name: CI/CD

on:
  push:
    branches:
      - main
    pull_requests:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unittest
        run: cargo test
